### ISSUE TITLE
Using ColumnProps render parameter

### ISSUE THREAD

**Issue by mcallisto** [mcallisto/slinky-antd.g8#1]
In the `Table` component, `ColumnProps` (see [antd docs](https://ant.design/components/table/#Column)) is used to define the properties of each `Column`.

It comes with a `render = (Any, T, Double) => typings.reactLib.reactMod.ReactNode` parameter function, that should be used to render the content of the cell according to what comes from the `dataSource`.

The `Any` parameter is the content of the `dataSource`, while the `Double` seems a counter for the row.

So far I have not been able to implement render, thus limiting what it can be shown into the cell to `String` text only. Specifically I have not been able to return any `ReactNode` element that then appears in the cell.

**Comment by mcallisto** [comment]
This is working, since `ReactNode` can be a `String`.

```
 render = (text, record, index) =>
  console.log("text: " + text)
  console.log("record: " + JSON.stringify(record))
  console.log("index: " + index)
  text.toString           
```
`record` is an object containing the whole `dataSource` row.

The problem now is to make a `ReactNode` of something like `span(text.toString)` or `Button(Button.Props())(text.toString)`.

**Comment by oyvindberg** [comment]
It seems both this and #2 is essentially the same issue - you have problems creating a `typings.reactLib.readMod.ReactNode` from Slinky. 
You'll have two choices:
- provide your own versions of all props traits to use Slinky's equivalent of `ReactNode`.
- provide (implicit maybe) converters (casting) between ScalablyTyped and Slinky types.

If you have a look at the definition of `ReactNode` you see the following:
```scala
type ReactNode = js.UndefOr[ReactChild | ReactFragment | ReactPortal | scala.Boolean | scala.Null]
type ReactText = java.lang.String | scala.Double
type ReactChild = ReactElement[js.Any] | ReactText
type ReactFragment = js.Object | ReactNodeArray
// +++
```
In essence, it can be *anything* React can render. In particular, it can be a `ReactElement, which is the vdom object generated for a rendered component. 

Just to get things going, try this:
```scala
def convert(x: slinky.core.facade.ReactElement): typings.reactLib.readMod.ReactNode = x.asInstanceOf[typings.reactLib.readMod.ReactNode]
```
I'm just guessing this part, but if not exactly this it should be something close

**Comment by mcallisto** [comment]
Thank you for your help!

I would prefer to avoid, if possible, to provide my own traits.

I like your suggested solution, very straightforward, and I remember trying something similar, but it doesn't seem to work.

If I change from
`addonBefore = "Before text"`
to
``addonBefore = Icon(IconProps(`type` = "home")).asInstanceOf[typings.reactLib.reactMod.ReactNode]``
the project compiles but once opened in a browser it doesn't show, giving the following error.

```
Warning: Failed prop type: Invalid prop `addonBefore` supplied to `Input`, expected a ReactNode.
    in Input (created by App)
    in App checkPropTypes.js:20
    printWarning checkPropTypes.js:20
    checkPropTypes checkPropTypes.js:82
    React 2
    renderInput$1__p1__sjs_js_Array ExternalComponent.scala:65
    1 App.scala:197
    apply__O__O AnonFunctions.scala:27
    slinky$core$FunctionalComponent$$$anonfun$apply$1__sjs_js_Object__F1__sr_ObjectRef__Lslinky_core_facade_ReactElement FunctionalComponent.scala:93
    elem$1 FunctionalComponent.scala:92
```
Any idea?

**Comment by mcallisto** [comment]
Wondering if this discussion is relevant and could help
https://gitter.im/shadaj/slinky?at=5b8f286ec2bd5d117a1e0e06

**Comment by oyvindberg** [comment]
I just gave it a shot with your project now, try this:
```scala
ColumnProps(title = "Name", dataIndex = "name", key = "name", render = (x, _, _) => span("custom: " + x)().asInstanceOf[typings.reactLib.reactMod.ReactNode]),
```

The clue seemed to be the last set of parents to obtain the `ReactElement`
