### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by mcallisto** [mcallisto/slinky-antd.g8#3]
The current `Form` and `FormItem` components via `react-slinky-facade` seem to have no props.
They are ok for layout but still missing all the validation and submission mechanisms, see https://ant.design/components/form/#API

**Comment by mcallisto** [comment]
Note https://github.com/oleg-py/arcomage-challenge/blob/d172e524f7fa372467f54f67a96ef1ef5b205afb/frontend/src/main/scala/ac/frontend/components/CustomConditionsForm.scala

**Comment by oyvindberg** [comment]
I updated my demo with a validation component that i ported https://github.com/oyvindberg/ScalablyTypedDemos/commit/46b85cc760bdb7ae9454a47924e2a1a7062f0415

**Comment by mcallisto** [comment]
@oyvindberg thank you, but I cannot find to a working way to translate your demo into Slinky. I know you are not too much into Slinky but possibly you have better overall ideas than me.
Here below a (simplified, no `Input` fields) try:

```
import typings.antdLib.antdLibComponents.{Button, FormItem, Input, Form => FormAlt}
import typings.antdLib.esFormFormMod.{FormCreateOption, FormProps, GetFieldDecoratorOptions, ValidationRule, WrappedFormUtils, default => Form}
import typings.reactLib.ScalableSlinky._
...

object Demo {

  @react class App extends StatelessComponent {

    case class Props(form: WrappedFormUtils[js.Object])

    val handleSubmit: FormEventHandler[js.Any] = e => {
      e.preventDefault()
      props.form.validateFields((err, values) => {
        if (js.isUndefined(err)) {
          console.log(s"Received values of form: $values")
        }
      })
    }

    def render = {
      FormAlt.props(
        FormProps(
          labelCol = ColProps(span = 5),
          wrapperCol = ColProps(span = 12),
          onSubmit = handleSubmit
        ))(
        FormItem.props(
          FormItemProps(wrapperCol = ColProps(span = 12, offset = 5)))(
          Button.props(ButtonProps(
            `type` = antdLibStrings.primary,
            htmlType = antdLibStrings.submit))("Submit")
        )
      )
    }
  }

  val Component = Form
    .create(FormCreateOption(name = "coordinated"))(
      js.constructorOf[App] // grab the javascript value of the class itself, this would be easier with functional component
    )
    .asInstanceOf[ComponentType[js.Object]] // drop too complex type
}
```

If I understand correctly, the idea is to create the final component to be used by calling the `Form.create` method, passing as `props` the javascript value of the component class itself. Is that right?

Although this object compiles, I have plenty of doubts about it being correct.
And then, afterwards, I am not even sure how to use `Demo.Component` of type `ComponentType[js.Object]` in the rest of the code, is not a `ReactElement`.

If you have time, any help into the right direction is very much appreciated.

**Comment by oyvindberg** [comment]
A `ComponentType` is the name of a react component that is either a class
or a function. `Form.create` takes a component and returns a component. The
result of that, `Component` here, is what you pass into `ExternalComponent`
or whatever the slinky thing was called. Does that help?

**Comment by mcallisto** [comment]
Ok, I think I am following you.

I already tried this (alway assuming that the `Demo` object is correct):

```
object Mario extends ExternalComponentNoProps {
  override val component = Demo.Component
}
```
and then
```
...
    val renderDemo: ReactElement = section(
      h2("Demo"),
      Mario()
    )
...
```
but I just get an ugly error when I see the app in the browser
`TypeError: $this.__proto__.constructor._base is undefined`

**Comment by oyvindberg** [comment]
`js.constructorOf[App] ` seems wrong in your code. You're getting the javascript constructor of your slinky scala class, not of the react component it wraps. That way react won't know what to do with it.

I'm not sure, but I think you can use `slinky.core.ReactComponentClass` for this:
```scala
Form.create(App: ReactComponentClass) //if you change `App` to object
```

**Comment by mcallisto** [comment]
Modified into this, at least it compiles

```
  @react object App {

    case class Props(form: WrappedFormUtils[js.Object])

    val component = FunctionalComponent[Props] { props =>
    ...
    }

  val Component = Form
    .create(FormCreateOption(name = "coordinated"))(
      App.asInstanceOf[ReactComponentClass[_]]
    )
    .asInstanceOf[ComponentType[js.Object]] // drop too complex type
}
```

but I get this browser error:

``Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Form(WrappedComponent)`.``

Sorry, I understand this is frustrating, feel free to quit here.
Maybe I should open a dedicated branch, at least the code can be reproduced and run.

**Comment by oyvindberg** [comment]
Try to not cast `App`, but to use the conversions for instance `ReactComponentClass.functionalComponentToClass(App)`

**Comment by mcallisto** [comment]
:+1: got it, this works:

```
val Component = Form
    .create(FormCreateOption(name = "coordinated"))(
      ReactComponentClass.functionalComponentToClass(App.component)
    )
    .asInstanceOf[ComponentType[js.Object]] // drop too complex type
```

Many thanks, I was quite lost! I will try to continue (and hopefully finish) tomorrow...
