### ISSUE TITLE
Form.create with additional props

### ISSUE THREAD

**Issue by mcallisto** [mcallisto/slinky-antd.g8#4]
How to add props to the `CoordinatedDemo.Component` component and its inner `App` component?

Without additional props there is no way to propagate outside the component(s) the values entered in the form.

**Comment by mcallisto** [comment]
@oyvindberg any idea on this?

I am stuck on the most basic, if I change from:
`case class Props(form: WrappedFormUtils[js.Object])`
to
`case class Props(form: WrappedFormUtils[js.Object], str: String)`
where and how in Form.create I can pass the `str` param?

**Comment by oyvindberg** [comment]
I added a commit to my demo which shows how to do it https://github.com/oyvindberg/ScalablyTypedDemos/commit/23bfb77781568feafcff70636a1b0e47ffe13eeb

It's a pretty typical way of doing things in javascript, which is irritating in scala. If you'll do it many times i suppose a facade function like [this](https://github.com/oyvindberg/ScalablyTypedDemos/blob/master/material-ui/src/main/scala/demo/Demo.scala#L157-L160) one for `@material-ui/core` would be useful

**Comment by mcallisto** [comment]
> I added a commit to my demo which shows how to do it [oyvindberg/ScalablyTypedDemos@23bfb77](https://github.com/oyvindberg/ScalablyTypedDemos/commit/23bfb77781568feafcff70636a1b0e47ffe13eeb)

Great, thank you @oyvindberg, I see the logic, almost there.
I will have a `CoordinatedDemo.Component` like this:
```
val Component: ComponentType[App.Props] = {
  val originalComponent = ReactComponentClass.functionalComponentToClass(App.component)
  val newComponent = Form.create(FormCreateOption[App.Props](name = "coordinated"))(originalComponent)
  newComponent.asInstanceOf[ComponentType[App.Props]]
}
```

but I miss how to pass the props to my component created with` ExternalComponent...`

```
object CoordinatedControls extends ExternalComponentNoProps {
  val titleProps = new CoordinatedDemo.App.Props(noteTitle = "Input note here")
  override val component = CoordinatedDemo.Component // doesn't have a props method to pass titleProps
}
```

**Comment by oyvindberg** [comment]
Well, `CoordinateDemo.Component` is now like a normal (ScalablyTyped) component, so you could use it with `.props(...)`.
To slinkify it, cant you say `type Props = App.Props`?

**Comment by mcallisto** [comment]
Put the work in progress in a separate branch. Two problems:

1. As reported
```
[error] [...] value props is not a member of typings.reactLib.reactMod.ComponentType[hello.world.CoordinatedDemo.App.Props]
[error]   override val component = CoordinatedDemo.Component.props(titleProp)
```

2. I thought the Slinky functional component could work with the `WithForm` trait, but it throws a compile error
```
[error] [...]CoordinatedDemo.scala:22:4: type mismatch;
[error]  found   : hello.world.CoordinatedDemo.App.Props
[error]  required: hello.world.CoordinatedDemo.App.Props with hello.world.CoordinatedDemo.App.WithForm
[error]   @react object App {
[error]    ^
```

**Comment by mcallisto** [comment]
With the simplified version adopted in the `better` branch, see https://github.com/mcallisto/slinky-antd.g8/blob/better/src/main/g8/src/main/scala/%24package%24/CoordinatedDemo.scala

* Problem 2. apparently solved 
* Problem 1. now `CoordinatedDemo.Component` shows a `props()` method, but needs a `scala.scalajs.js.Object` and not a `CoordinatedDemo.Props` as I was hoping. Also don't know if, after applying the `props()` method, `val component` will be of the type expected by `ExternalComponent...`

**Comment by oyvindberg** [comment]
So I integrated changes from both repos into [this commit](https://github.com/oyvindberg/ScalablyTypedDemos/pull/10/commits/691aff93c7f37b1ae26005a4afe4c200c36f24f0), including solving this problem.

Let's work through both antd and react-router-dom in https://github.com/oyvindberg/ScalablyTypedDemos/pull/10 there and see how good we can get it :)
